VSCP-101: Added jira component update (#171)

diff --git a/cicd/Dockerfile b/cicd/Dockerfile
--- a/cicd/Dockerfile
+++ b/cicd/Dockerfile
@@ -6,9 +6,9 @@ FROM ghcr.io/vcp-vsa-control-plane/vsa-builder:v2
 #ARG GO_FILENAME_SHA
 
 ARG RUNNER=github
-ARG GO_VERSION
-ARG GO_FILENAME
-ARG GO_FILENAME_SHA
+#ARG GO_VERSION
+#ARG GO_FILENAME
+#ARG GO_FILENAME_SHA
 
 USER root
 
@@ -21,12 +21,12 @@ RUN mkdir -p /usr/local/go && chown github:github /usr/local/go
 
 USER github
 
-RUN cd /tmp && curl -y 20 -Y 1000 --retry 5 --retry-max-time 30 --connect-timeout 30 --no-progress-meter -SLO https://go.dev/dl/${GO_FILENAME} ; \
-  echo "${GO_FILENAME_SHA} ${GO_FILENAME}" | sha256sum -c - || exit 1 ; \
-  cd /usr/local && \
-  tar zxf /tmp/${GO_FILENAME} && \
-  rm -rf /tmp/* && \
-  /usr/local/go/bin/go version > ~/go-version
+#RUN cd /tmp && curl -y 20 -Y 1000 --retry 5 --retry-max-time 30 --connect-timeout 30 --no-progress-meter -SLO https://go.dev/dl/${GO_FILENAME} ; \
+#  echo "${GO_FILENAME_SHA} ${GO_FILENAME}" | sha256sum -c - || exit 1 ; \
+#  cd /usr/local && \
+#  tar zxf /tmp/${GO_FILENAME} && \
+#  rm -rf /tmp/* && \
+#  /usr/local/go/bin/go version > ~/go-version
 
 COPY bin/build/linux/vsacictl /usr/local/bin/
 
