VSCP-791: Artifact URLs fix for final tag (#553)
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

diff --git a/.github/workflows/build_common.yaml b/.github/workflows/build_common.yaml
--- a/.github/workflows/build_common.yaml
+++ b/.github/workflows/build_common.yaml
@@ -252,11 +252,16 @@ jobs:
         run: |
           IMAGES=("core" "google-proxy" "vcp-db-migrate" "vcp-worker")
           for IMAGE in "${IMAGES[@]}"; do
-            ARTIFACT_URL=$(gcloud artifacts docker images list ${{vars.AR_GCP_REGION}}-docker.pkg.dev/${{vars.AR_GCP_PROJ}}/${{vars.AR_GCP_REPO}}/${IMAGE} \
-            --include-tags \
-            --format="value(DIGEST)" \
-            --filter="TAGS:${{ inputs.tag }}" | awk '{print "${{vars.AR_GCP_REGION}}-docker.pkg.dev/${{vars.AR_GCP_PROJ}}/${{vars.AR_GCP_REPO}}/'${IMAGE}'@" $1}')
-            echo "${IMAGE//-/_}_ARTIFACT_URL=${ARTIFACT_URL}" >> $GITHUB_ENV
+            DIGEST=$(gcloud artifacts docker images describe ${{ vars.AR_GCP_REGION }}-docker.pkg.dev/${{ vars.AR_GCP_PROJ }}/${{ vars.AR_GCP_REPO }}/${IMAGE}:${{ inputs.tag }} \
+              --format="value(image_summary.digest)")
+    
+            if [[ -n "$DIGEST" ]]; then
+              ARTIFACT_URL="${{ vars.AR_GCP_REGION }}-docker.pkg.dev/${{ vars.AR_GCP_PROJ }}/${{ vars.AR_GCP_REPO }}/${IMAGE}@${DIGEST}"
+              echo "${IMAGE//-/_}_ARTIFACT_URL=${ARTIFACT_URL}" >> $GITHUB_ENV
+            else
+              echo "Failed to fetch digest for image: ${IMAGE}:${{ inputs.tag }}"
+              exit 1
+            fi
           done
 
       - name: Generate and Sign Payloads
