VSCP-5190: trivy scan disabled (#3264)

diff --git a/.github/workflows/build_common.yaml b/.github/workflows/build_common.yaml
--- a/.github/workflows/build_common.yaml
+++ b/.github/workflows/build_common.yaml
@@ -508,6 +508,7 @@ jobs:
           IMAGE: ${{ matrix.image }}
 
   trivy_scan_image:
+    if: ${{ false }}
     name: Run trivy scan on the container images
     needs: [ build_and_publish ]
     runs-on: [ self-hosted,linux ]
@@ -531,38 +532,38 @@ jobs:
       - name: Ensure output directory exists
         run: mkdir -p repo-dir2
 
-      - name: Run Trivy vulnerability scanner - Table format
-        if: ${{ inputs.trivy_scan_format == 'table' }}
-        uses: aquasecurity/trivy-action@master
-        with:
-          image-ref: ${{ matrix.image == 'cloud-backup-adc' && format('ghcr.io/vcp-vsa-control-plane/{0}/{1}:2.9', vars.AR_IMAGE_PATH, matrix.image) || format('ghcr.io/vcp-vsa-control-plane/{0}/{1}:{2}', vars.AR_IMAGE_PATH, matrix.image, inputs.tag) }}
-          format: ${{ inputs.trivy_scan_format }}
-          exit-code: 1
-          ignore-unfixed: true
-          severity: HIGH,CRITICAL
+      #- name: Run Trivy vulnerability scanner - Table format
+      #  if: ${{ inputs.trivy_scan_format == 'table' }}
+      #  uses: aquasecurity/trivy-action@master
+      #  with:
+      #    image-ref: ${{ matrix.image == 'cloud-backup-adc' && format('ghcr.io/vcp-vsa-control-plane/{0}/{1}:2.9', vars.AR_IMAGE_PATH, matrix.image) || format('ghcr.io/vcp-vsa-control-plane/{0}/{1}:{2}', vars.AR_IMAGE_PATH, matrix.image, inputs.tag) }}
+      #    format: ${{ inputs.trivy_scan_format }}
+      #    exit-code: 1
+      #    ignore-unfixed: true
+      #    severity: HIGH,CRITICAL
 
-      - name: Run Trivy vulnerability scanner
-        if: ${{ inputs.trivy_scan_format == 'sarif' }}
-        uses: aquasecurity/trivy-action@master
-        with:
-          image-ref: ${{ matrix.image == 'cloud-backup-adc' && format('ghcr.io/vcp-vsa-control-plane/{0}/{1}:2.9', vars.AR_IMAGE_PATH, matrix.image) || format('ghcr.io/vcp-vsa-control-plane/{0}/{1}:{2}', vars.AR_IMAGE_PATH, matrix.image, inputs.tag) }}
-          format: 'sarif'
-          output: 'repo-dir2/trivy-${{ matrix.image }}.sarif'
+      #- name: Run Trivy vulnerability scanner
+      #  if: ${{ inputs.trivy_scan_format == 'sarif' }}
+      #  uses: aquasecurity/trivy-action@master
+      #  with:
+      #    image-ref: ${{ matrix.image == 'cloud-backup-adc' && format('ghcr.io/vcp-vsa-control-plane/{0}/{1}:2.9', vars.AR_IMAGE_PATH, matrix.image) || format('ghcr.io/vcp-vsa-control-plane/{0}/{1}:{2}', vars.AR_IMAGE_PATH, matrix.image, inputs.tag) }}
+      #    format: 'sarif'
+      #    output: 'repo-dir2/trivy-${{ matrix.image }}.sarif'
 
-      - name: upload trivy scan results
-        if: ${{ inputs.trivy_scan_format == 'sarif' }}
-        shell: bash -e {0}
-        run: |
-          if [ -f repo-dir2/trivy-${{ matrix.image }}.sarif ]; then
-            curl -L -X POST -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            -H "Authorization: Bearer ${{ secrets.GHVSA_PAT}}" \
-            https://api.github.com/repos/VCP-VSA-control-Plane/vsa-control-plane/code-scanning/sarifs \
-            -d "{\"commit_sha\":\"${{ github.sha }}\",\"ref\":\"refs/heads/main\",\"sarif\":\"$(gzip -c repo-dir2/trivy-${{ matrix.image }}.sarif | base64 -w0)\"}"
-          else
-            echo "SARIF file for ${{ matrix.image }} not found."
-            exit 1
-          fi
+      #- name: upload trivy scan results
+      #  if: ${{ inputs.trivy_scan_format == 'sarif' }}
+      #  shell: bash -e {0}
+      #  run: |
+      #    if [ -f repo-dir2/trivy-${{ matrix.image }}.sarif ]; then
+      #      curl -L -X POST -H "Accept: application/vnd.github+json" \
+      #      -H "X-GitHub-Api-Version: 2022-11-28" \
+      #      -H "Authorization: Bearer ${{ secrets.GHVSA_PAT}}" \
+      #      https://api.github.com/repos/VCP-VSA-control-Plane/vsa-control-plane/code-scanning/sarifs \
+      #      -d "{\"commit_sha\":\"${{ github.sha }}\",\"ref\":\"refs/heads/main\",\"sarif\":\"$(gzip -c repo-dir2/trivy-${{ matrix.image }}.sarif | base64 -w0)\"}"
+      #    else
+      #      echo "SARIF file for ${{ matrix.image }} not found."
+      #      exit 1
+      #    fi
 
   send-slack-notification:
     if: ${{ inputs.send_slack_notification }}
