VSCP-467: trivy scan for container images (#442)
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -191,6 +191,54 @@ jobs:
             echo "BlackDuck scan completed for image: ${IMAGE}"
           done
 
+  trivy_scan_image:
+    name: Run trivy scan on the container images
+    needs: [create_pre_release_vsa_control_plane, generate_tag]
+    runs-on: [ self-hosted,linux ]
+    container:
+      image: ghcr.io/vcp-vsa-control-plane/vsacictl:v22
+      options: -v /var/run/docker.sock:/var/run/docker.sock --user root
+    permissions:
+      contents: read
+      packages: write
+      id-token: write
+      security-events: write
+    strategy:
+      matrix:
+        image:
+          - "google-proxy"
+          - "core"
+          - "vcp-db-migrate"
+          - "vcp-worker"
+          - "cloud-backup-adc"
+
+    steps:
+      - name: Log in to the Container registry
+        run: |
+          echo "${{ secrets.GHVSA_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+
+      - name: Run Trivy vulnerability scanner
+        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
+        with:
+          image-ref: ghcr.io/vcp-vsa-control-plane/${{ matrix.image }}:$([[ "${{ matrix.image }}" == "cloud-backup-adc" ]] && echo "2.7" || echo "${{ needs.generate_tag.outputs.newTag }}")
+          format: 'sarif'
+          output: 'repo-dir2/trivy-${{ matrix.image }}.sarif'
+
+      - name: upload trivy scan results
+        shell: bash -e {0}
+        run: |
+          if [ -f repo-dir2/trivy-${{ matrix.image }}.sarif ]; then
+            curl -L -X POST -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -H "Authorization: Bearer ${{ secrets.GHVSA_PAT}}" \
+            https://api.github.com/repos/VCP-VSA-control-Plane/vsa-control-plane/code-scanning/sarifs \
+            -d "{\"commit_sha\":\"${{ github.sha }}\",\"ref\":\"refs/heads/main\",\"sarif\":\"$(gzip -c repo-dir2/trivy-${{ matrix.image }}.sarif | base64 -w0)\"}"
+          else
+            echo "SARIF file for ${{ matrix.image }} not found." 
+            exit 1
+          fi          
+          
+
   send-slack-notification:
     needs: [generate_tag,create_pre_release_vsa_control_plane, update_jira_component_version]
     runs-on: [ ubuntu-22.04 ]
